default: &default
  adapter: mysql2
  pool: 5
  username: root
  password:
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: homeo_development

test:
  <<: *default
  database: homeo_test

production:
  <<: *default
  database: homeo_production
